[package]
name = "yi-edit"
description = "Yi Edit —— 极简跨平台代码编辑器"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
yi-edit-core = { path = "../core" }
yi-edit-fileio = { path = "../fileio" }
eframe = "0.36"
egui = "0.36"
image = { version = "0.25", default-features = false, features = ["png"] }

[[bin]]
name = "yi-edit"
path = "src/main.rs"

[[bin]]
name = "yi-shotcheck"
path = "src/bin/shotcheck.rs"
