use std::path::PathBuf;
use std::sync::Arc;

use yi_edit_core::{highlight_line, Pos, SearchOptions, TokenKind};
use yi_edit_session::browser::{self, Listing};
use yi_edit_session::ime::ImeEffect;
use yi_edit_session::jump::JumpMap;
use yi_edit_session::Editor;

use crate::ime_adapter::ImeAdapter;
use crate::shot::Shot;
use crate::theme as th;

fn mono() -> egui::FontId { egui::FontId::monospace(th::FONT_SIZE) }
fn sans(s: f32) -> egui::FontId { egui::FontId::proportional(s) }
fn token_color(k: TokenKind) -> egui::Color32 { match k { TokenKind::Text=>th::TEXT, TokenKind::Keyword=>egui::Color32::from_rgb(255,122,178), TokenKind::Type=>egui::Color32::from_rgb(90,200,184), TokenKind::Str=>egui::Color32::from_rgb(255,159,106), TokenKind::Number=>egui::Color32::from_rgb(168,216,122), TokenKind::Comment=>egui::Color32::from_rgb(108,140,98), TokenKind::Punct=>th::TEXT_DIM } }

pub fn install_fonts(ctx: &egui::Context) {
    const C: &[&str] = &["/System/Library/Fonts/SFNSMono.ttf","/usr/share/fonts/truetype/droid/DroidSansFallbackFull.ttf","/usr/share/fonts/truetype/wqy/wqy-microhei.ttf","/usr/share/fonts/opentype/noto/NotoSansCJKsc-Regular.otf","C:\\Windows\\Fonts\\msyh.ttf"];
    let Some((p,b))=C.iter().find_map(|p|std::fs::read(p).ok().filter(|b|b.len()>4096).map(|b|(*p,b))) else { eprintln!("FONT: no CJK font"); return; };
    let mut f=egui::FontDefinitions::default(); f.font_data.insert("cjk".into(),Arc::new(egui::FontData::from_owned(b))); for fam in [egui::FontFamily::Proportional,egui::FontFamily::Monospace]{f.families.entry(fam).or_default().push("cjk".into());} ctx.set_fonts(f); eprintln!("FONT: {p}");
}
pub fn install_style(ctx:&egui::Context){let mut v=egui::Visuals::dark();v.panel_fill=th::BG;v.window_fill=th::CHROME;v.widgets.inactive.bg_fill=th::CONTROL;v.widgets.hovered.bg_fill=th::CONTROL_HOVER;v.widgets.active.bg_fill=th::ACCENT;ctx.set_visuals(v);}

pub struct YiEdit { ed: Editor, path: String, search: String, replace: String, hits: Vec<Pos>, ime: ImeAdapter, preedit: String, preedit_range: Option<std::ops::Range<usize>>, listing: Option<Listing>, show_side: bool, show_jump: bool, show_find: bool, close_dialog: bool, force_close: bool, shot: Shot }
impl YiEdit {
 pub fn new(arg:Option<PathBuf>)->Self{let(ed,path)=match arg{Some(p)=>match Editor::open(&p){Ok(e)=>(e,p.to_string_lossy().into()),Err(e)=>{let mut x=Editor::empty();x.status=format!("open failed: {e}");(x,p.to_string_lossy().into())}},None=>(Editor::empty(),String::new())};let mut x=Self{ed,path,search:String::new(),replace:String::new(),hits:Vec::new(),ime:ImeAdapter::default(),preedit:String::new(),preedit_range:None,listing:None,show_side:true,show_jump:true,show_find:false,close_dialog:false,force_close:false,shot:Shot::from_env()};x.refresh();x}
 fn refresh(&mut self){let d=self.ed.path.as_ref().and_then(|p|browser::dir_for(p)).or_else(||std::env::current_dir().ok());if let Some(d)=d{self.listing=browser::list_dir(&d,false).ok();}}
 fn opts(&self)->SearchOptions{SearchOptions::exact()}
 fn insert(&mut self,t:&str){if self.ed.insert_text(t){self.ed.status=format!("inserted {} chars",t.chars().count());}}
 fn delete_surrounding(&mut self,before:usize,after:usize){let mut a=self.ed.cursor;for _ in 0..before{a=self.ed.prev_pos(a)}let mut b=self.ed.cursor;for _ in 0..after{b=self.ed.next_pos(b)}if a!=b{if let Some(d)=self.ed.doc_mut(){d.delete(a,b);self.ed.cursor=a;self.ed.invalidate_states(a.line);}}}
 fn ime(&mut self,ev:&egui::ImeEvent){match self.ime.feed(ev){AdapterEffect::Commit(t)=>{self.insert(&t);self.ed.commit_undo_group();},AdapterEffect::DeleteSurrounding{before_chars,after_chars}=>self.delete_surrounding(before_chars,after_chars),AdapterEffect::ClearPreedit=>{self.preedit.clear();self.preedit_range=None},AdapterEffect::None=>{}}let p=self.ime.preedit();self.preedit=p.text;self.preedit_range=p.active_range_chars;}
 fn keys(&mut self,ctx:&egui::Context){for ev in ctx.input(|i|i.events.clone()){match ev{egui::Event::Ime(e)=>self.ime(&e),egui::Event::Copy=>{if let Some(t)=self.ed.selected_text(){ctx.copy_text(t)}},egui::Event::Cut=>{if let Some(t)=self.ed.cut_selection(){ctx.copy_text(t)}},egui::Event::Paste(t)=>self.insert(&t.replace("\r\n","\n")),egui::Event::Text(t)=>self.insert(&t),egui::Event::Key{key,pressed:true,modifiers,..}=>{if modifiers.command&&key==egui::Key::A{self.ed.select_all()}else if key==egui::Key::S{let _=self.ed.save()}},_=>{}}}}
 fn bar(&mut self,ui:&mut egui::Ui){ui.horizontal(|ui|{ui.label(egui::RichText::new("Yi Edit").font(sans(14.0)));if ui.button("侧栏").clicked(){self.show_side=!self.show_side}if ui.button("跳转").clicked(){self.show_jump=!self.show_jump}if ui.button("打开").clicked(){let p=PathBuf::from(self.path.clone());if p.exists(){if let Ok(e)=Editor::open(&p){self.ed=e;self.refresh()}}}if ui.button("保存").clicked(){let _=self.ed.save()}ui.add_sized([260.,24.],egui::TextEdit::singleline(&mut self.path).hint_text("文件路径"));if ui.button("查找").clicked(){self.show_find=!self.show_find}})}
 fn sidebar(&mut self,ui:&mut egui::Ui){ui.label("文件");if let Some(l)=self.listing.clone(){ui.label(l.dir.to_string_lossy());for e in l.entries{let label=if e.is_dir{format!("{}/",e.name)}else{e.name};if ui.button(label).clicked()&& !e.is_dir{if let Ok(x)=Editor::open(&e.path){self.ed=x}}}}}
 fn editor(&mut self,ui:&mut egui::Ui){ui.spacing_mut().item_spacing.y=0.;let rh=ui.text_style_height(&egui::TextStyle::Monospace);let total=self.ed.line_count().max(1);egui::ScrollArea::both().show_rows(ui,rh,total,|ui,rows|{for row in rows{let text=self.ed.line(row);let(spans,_)=highlight_line(&text,self.ed.lang,self.ed.state_at(row));let(r,res)=ui.allocate_exact_size(egui::vec2(ui.available_width().max(600.),rh),egui::Sense::click());let p=ui.painter_at(r);let x=r.min.x+th::GUTTER_W;p.text(egui::pos2(x-8.,r.min.y),egui::Align2::RIGHT_TOP,(row+1).to_string(),mono(),th::TEXT_DIM);let mut job=egui::text::LayoutJob::default();for s in spans{job.append(&text[s.start..s.end],0.,egui::TextFormat{font_id:mono(),color:token_color(s.kind),..Default::default()})}p.galley(egui::pos2(x,r.min.y),ui.painter().layout_job(job),th::TEXT);if row==self.ed.cursor.line&&!self.preedit.is_empty(){let cx=x+ui.painter().layout_no_wrap(&text[..self.ed.cursor.col.min(text.len())],mono(),th::TEXT).rect.width();p.text(egui::pos2(cx,r.min.y),egui::Align2::LEFT_TOP,format!("{}",self.preedit),mono(),th::ACCENT);let caret=egui::Rect::from_min_size(egui::pos2(cx,r.min.y),egui::vec2(2.,rh));ui.ctx().send_viewport_cmd(egui::ViewportCommand::IMERect(caret));}if res.clicked(){self.ed.commit_undo_group();}}})}
 fn guard(&mut self,ctx:&egui::Context){if ctx.input(|i|i.viewport().close_requested())&&!self.force_close&&!self.shot.active()&&self.ed.is_dirty(){ctx.send_viewport_cmd(egui::ViewportCommand::CancelClose);self.close_dialog=true}}
}
impl eframe::App for YiEdit{fn ui(&mut self,ui:&mut egui::Ui,_:&mut eframe::Frame){let ctx=ui.ctx().clone();self.shot.tick(&ctx);self.guard(&ctx);self.keys(&ctx);ui.vertical(|ui|{self.bar(ui);if self.show_find{ui.horizontal(|ui|{ui.add(egui::TextEdit::singleline(&mut self.search));if ui.button("查找").clicked(){self.hits=self.ed.search(&self.search,self.opts()).0}})}ui.horizontal(|ui|{if self.show_side{ui.allocate_ui_with_layout(egui::vec2(th::SIDEBAR_W,ui.available_height()),egui::Layout::top_down(egui::Align::Min),|ui|self.sidebar(ui));}self.editor(ui);if self.show_jump{let r=ui.allocate_response(egui::vec2(th::JUMP_W,ui.available_height()),egui::Sense::click());ui.painter().rect_filled(r.rect,0.,th::CHROME);if let Some(m)=JumpMap::new(r.rect.height()as u32,self.ed.line_count()){let(t,b)=m.viewport_band(self.ed.cursor.line,1);ui.painter().rect_filled(egui::Rect::from_min_max(egui::pos2(r.rect.min.x,r.rect.min.y+t as f32),egui::pos2(r.rect.max.x,r.rect.min.y+b as f32)),0.,th::ACCENT)}}});ui.separator();ui.label(self.ed.status_bar().position_text())});if self.close_dialog{egui::Window::new("有未保存的修改").show(&ctx,|ui|{if ui.button("保存并退出").clicked(){let _=self.ed.save();self.force_close=true;ctx.send_viewport_cmd(egui::ViewportCommand::Close)}if ui.button("不保存退出").clicked(){self.force_close=true;ctx.send_viewport_cmd(egui::ViewportCommand::Close)}if ui.button("取消").clicked(){self.close_dialog=false}})}}}
#[allow(dead_code)]const _WELCOME_IS_SHARED:&str=WELCOME;
